---
- name: "Validate Common Criteria recommendations on Apache Tomcat installation"
  hosts: "all"
  vars:
    jws_setup: true
    tomcat_version: 9.0.50
    download_url: https://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.zip
    jws_install_dir: /opt
    tomcat_zipfile: "{{ jws_install_dir }}/tomcat.zip"
    jws_home: "{{ jws_install_dir }}/apache-tomcat-{{ tomcat_version }}"
    jws_java_version: 1.8.0
    jws_listen_http_bind_address: 127.0.0.1
    jws_listen_http_port: 8081
  collections:
    - middleware_automation.jws
  roles:
    - jws

  pre_tasks:
    - name: "Download latest Apache Tomcat zip file from {{ download_url }}."
      get_url:
        url: "{{ download_url }}"
        dest: "{{ tomcat_zipfile }}"
      when:
        - download_url is defined

    - ansible.builtin.include_role:
        name: jws

  tasks:
    - meta: flush_handlers

  post_tasks:
    - ansible.builtin.include_role:
        name: ../../roles/jws_common_criteria
