---
- name: Converge
  hosts: all
  collections:
    - middleware_automation.wildfly
  vars:
    wildfly_home: '/opt/wildfly/wildfly-26.0.0.Final'
    java_home: '/usr/lib/jvm/jre-openjdk/'
    java_version: 1.8.0
    jdk_id: 'openjdk'
    jboss_home: /opt/wildfly/wildfly-26.0.0.Final
    wildfly_user: 'wildfly'
    wildfly_group: "{{ wildfly_user }}"
  tasks:
    - name: Include wildfly_install role
      ansible.builtin.include_role:
        name: wildfly_install

    - name: Include wildfly_systemd role
      ansible.builtin.include_role:
        name: wildfly_systemd
    - meta: flush_handlers

  post_tasks:
    - name: "Run Common Criteria role on setup"
      ansible.builtin.include_role:
        name: ../../roles/wildfly_common_criteria
