---
name: CI
"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.9"]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ansible_collections/middleware_automation/common_criteria

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install yamllint, ansible and molecule
        run: |
          python -m pip install --upgrade pip
          pip install yamllint 'molecule[docker]~=3.5.2' ansible-core flake8 ansible-lint voluptuous

      - name: Run sanity tests
        run: ansible-test sanity
        working-directory: ./ansible_collections/middleware_automation/common_criteria

      - name: Run molecule test
         run: |
           ansible-galaxy collection install -r molecule/requirements.yml
           molecule test --all
         env:
           PY_COLORS: "1"
           ANSIBLE_FORCE_COLOR: "1"
         working-directory: ./ansible_collections/redhat/jws
